# Name and metadata of your task
task_name: '$SONO Listening Task'
author: 'Reverie Field Project'
description: 'Participate in the Reverie Field Project Listening Task to earn $SONO KPL tokens. Reverie Field Project is a Telegram mini-app game where players earn rewards by actively listening to various sounds. This task tracks and caches player activity and ensure fair reward distribution. Player data is fetched from the server, cached for faster access, and used to validate listening activity. The bounty per round is 1000 $SONO, which will be divided among users who have demonstrated active participation by increasing their in-game listening points. Telegram bot: https://t.me/NotRadioBot or @NotRadioBot. Start your journey!'
repositoryUrl: 'https://github.com/CatchTheRecord/reverie-field-compute-task' # Replace with your own repo URL
imageUrl: 'https://catchtherecord.com/files/1305664/qmuuddwu1pgtyx4k7hdhnmjchtja4xjbfgdsswpwzu1py9.png'
infoUrl: 'infoUrl'

# Task executable network: DEVELOPMENT, ARWEAVE, or IPFS
# IPFS is the default value, as the CLI automatically manages the upload process via the Koii Storage SDK.
task_executable_network: 'IPFS'

# Task audit program: Path to your executable webpack if the selected network is IPFS. In the case of DEVELOPMENT, name it as main.
task_audit_program: 'dist/main.js'

# Round time: The total duration of your task, measured in slots (with each slot approximately equal to 408ms).
round_time: 450

# Audit window: The audit window should be greater than 1/3 of the round time.
audit_window: 160

# Submission window: The submission window should be greater than 1/3 of the round time.
submission_window: 160

# Minimum stake amount: The minimum amount of KOII that a user must stake in order to participate in the task.
minimum_stake_amount: 1.9

# Task Bounty Type: KOII, KPL
task_type: 'KPL'

# OPTIONAL (ONLY IF Task Type = KPL) : Token Mint Address, Fire Token as an example here. 
token_type: "n3Rep7GRh3jgkGXaULNu8WzfuwCC9Rcrv82mxzJMnnH"

# Total bounty amount: The total bounty amount that will be distributed to the task. (Not accepted in case of update task).
total_bounty_amount: 1000000
bounty_amount_per_round: 1000

# Allowed failed distributions: Number of times re-submission is allowed for the distribution list in case of an audit.
# It is also the number of rounds submission will be kept.
allowed_failed_distributions: 3

# Space: Space in MBs for the account size, that holds the task data.
# For testing tasks this can be set to 0.1, but for production it should be set to at least 1.
space: 2

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer to the type, value, description format shown below.

requirementsTags:
  - type: TASK_VARIABLE
    value: "TG_USERNAME"
    description: "Your username in the Reverie Field game and unique @username in Telegram"

# OPTIONAL variables for creating task / REQUIRED variables for updating task

# ONLY provide the task_id and migrationDescription if you are updating the task, otherwise leave blank.
# Task_id: Previous task ID.
task_id: 'Bw38LwJM9PbXuELdvYEm6ui28DwYzvfM5XVPZEfHHpsd'

# Migration description: Provide the description for changes made in the new version of the task.
migrationDescription: 'big logic update5'
